"""기능 ON/OFF 설정. STEP 메시지만 기본 활성화한다."""
ENABLE_STEP_MESSAGE = True
ENABLE_ENTRY_RADAR = False
ENABLE_1H_BRIEFING = False
ENABLE_DAILY_BRIEFING = False
ENABLE_WEEKLY_BRIEFING = False
ENABLE_GOOGLE_SHEET = False
ENABLE_AUTO_TRADE = False
